### ISSUE TITLE
Some numbers formatted with wrong font.

### ISSUE THREAD

**Issue by RolfBremer** [fenjalien/metro#13]
The formatted number uses the wrong font, if the group settings are as in the following sample:

```typ
#import "@preview/metro:0.1.1": *

#set page("a4")
#set text(size: 14pt)
#show math.equation: set text(font: "Cascadia Code", size: 22pt)

#metro-setup(
  group-digits: "integer",
  group-separator: ".",
  group-minimum-digits: 4,
  output-decimal-marker: ","
)

#table(
  columns: 2,

  [Test 1:], [#num(1234500.23)],
  [Test 2:], [#num(0.000130)],
  [Test 3:], [#num(100)],
  [Test 4:], [#num(1000)],
  [Test 5:], [#num(1.2)],
)
```
![image](https://github.com/fenjalien/metro/assets/46456966/02a96fab-6ac8-4e0a-8844-6f6c588dd5bb)

As shown in the resulting table, Test3 and Test4 are formatted with a different font. This seems to happen, if the length of the number is smaller than the defined `group-minimum-digits` and no significant fractional decimal places are given. Test5 shows, that even a short number is formatted right, if significant (>0) decimal places are in the fractional part of the number.

**Comment by fenjalien** [comment]
Looking further into this I believe this is because Cascadia Code does not have math glyphs so Typst falls back to the default font which does.

```typ

#num(1.2)

$100$

#[
  #show math.equation: set text(font: "Cascadia Code", fill: red)

  #num(1.2)

  $100$
]

#[
  #show math.equation: set text(font: "Fira Math", fill: blue)

  #num(1.2)

  $100$
]
```
![image](https://github.com/fenjalien/metro/assets/34489450/049adc10-4b7e-40de-a15a-67019417b4de)

**Comment by RolfBremer** [comment]
The font is a good tip, but I still think, it is a bug.
In the following example, the first and last numbers are formatted with the Cascadia font:

```typ
#[
  #show math.equation: set text(font: "Cascadia Code", fill: red)

  #num(10022)

  #num(0)

  #num(1.2)

  #num(10000.2)
]
```

![image](https://github.com/fenjalien/metro/assets/46456966/6e8ffd38-7416-4540-8075-8ca5946e5435)

**Comment by fenjalien** [comment]
I think the bug is when Typst decides when to fallback or not:
```typ
#show math.equation: set text(font: "Cascadia Code", fill: red)
#for test in (" ", "/", "^") {
  test = math.equation("1" + test + "0")
  repr(test)
  linebreak()
  test
  linebreak()
}
```
![image](https://github.com/fenjalien/metro/assets/34489450/4c65d954-54b8-422f-9d1a-ed998b5caa05)

Even if we could find all cases that it does I'm not sure what to do about it...
