### ISSUE TITLE
Feature Request: Add options for significant figures and decimal digits

### ISSUE THREAD

**Issue by trondhauklien** [fenjalien/metro#15]
It would be nice to be able to set the number of decimal digits or the number of significant figures as an option in the `num` and `qty` function. When displaying results in a table or importing data from external files, sometimes you want to adjust these parameters without loss of accuracy in the underlying data.

**Comment by fenjalien** [comment]
As of 0.3.0 rounding options have been added which allows you to round to a number of decimal places or significant figures :)
