### ISSUE TITLE
The render of pascal seems strange

### ISSUE THREAD

**Issue by xiaoxuan-yu** [fenjalien/metro#18]
I try to use metro v0.2.0 in my document and found the unit "pascal" is not rendered correctly. Specifically, it is a little wider than normal (it seems that an extra space is added to the unit). 
```typst
$ p_1 = qty(2.043,"pascal") \
  p_2 = 0.3268 "Pa" $
```
And the result is showed as below
![image](https://github.com/fenjalien/metro/assets/55308316/67e02a52-428c-4af6-9cc7-5d0e69ea2389)

Is that a designed behavior or a bug?

**Comment by fenjalien** [comment]
Unfortunately I can't reproduce this so I'm not sure whats going on here.

With the following code
```
#import "@preview/metro:0.2.0": *

$ p_1 = qty(2.043,"pascal") \
  p_2 = 0.3268 "Pa" $
```
on Typst 0.11 on the web app produces
![image](https://github.com/fenjalien/metro/assets/34489450/9902cf39-3cdf-471c-a4c8-28a91793a275)

Could you provide more details of when it occurs. A minimum code example would help as well.

**Comment by xiaoxuan-yu** [comment]
When I commented the font set for math equations, the render becomes correct. Seems like the font's fault.
