### ISSUE TITLE
Typos in manual

### ISSUE THREAD

**Issue by emilyyyylime** [fenjalien/metro#3]
Section 2.3.1 in `phrase`; typo 'othre'.
Towards the end of the section 3 first paragraph; confusing grammar.
Section 4.3 Powers first paragraph; two typos.

**Comment by emilyyyylime** [comment]
Let's move more typos here;
Confusing grammar towards the end of section 3 Meet the Units 
Two typos in 4.3 Powers

**Comment by fenjalien** [comment]
thanks!
