### ISSUE TITLE
Allow explicit sqrt

### ISSUE THREAD

**Issue by emilyyyylime** [fenjalien/metro#4]
I imagine this would work as `#unit("hertz per sqrt kilo watt hour")` (a very useful unit)
This would also come with a `sticky-sqrt` option

**Comment by fenjalien** [comment]
Would the output look something like this?
![image](https://github.com/fenjalien/metro/assets/34489450/865779b8-97c8-42ff-ab65-b00ab2af5e8f)

**Comment by emilyyyylime** [comment]
Yeah, or equivalent — I would imagine

**Comment by fenjalien** [comment]
Supported as of https://github.com/fenjalien/metro/commit/4e50ed17197d1b12955faec3814f9edeeb5d4edc and will be available in the next release. I should note you have to enable `power-half-as-sqrt` and use the "sqrt" as a function. I haven't updated the manual yet but you can see https://github.com/fenjalien/metro/blob/main/tests/unit/sqrt/
