### ISSUE TITLE
Feature Request: num-range as Typst equivalent of siunitx qtyrange

### ISSUE THREAD

**Issue by JamesxX** [fenjalien/metro#8]
As per title, num-range would be an excellent addition

**Comment by fenjalien** [comment]
I'm struggling to find motivation to implement this as I don't see what immediate benfit `#num-range(10, 30)` (or `numrange`) would have over `#num(10) to #num(30)`. Could you give an example of how you would use such a feature compared to not having it?

That being said if someone is to make a PR for this, I'm happy to accept it.

**Comment by trondhauklien** [comment]
Although I agree with @fenjalien that `#num-range(x, y)` might not be necessary, I miss the Siunitx qtyrange function in Typst. Something like `#qty-range(10, 30, " m / s ")` would make a lot of sense. It could render "10–30 m/s" or "10 to 30 m/s" depending on an option defining the range indicator. In Siunitx, this is implemented as an option `range-phrase`, which defaults to "to". They also point out that in some languages, an opening range phrase is requires (eg. "_from_ x to y"), implemented with an option `range-open-phrase`.

The grouping of units could be configurable, here with an example from the Siunitx manual:
```latex
\qtyrange{2}{4}{\degreeCelsius} \\
\qtyrange[range-units = bracket]{2}{4}{\degreeCelsius} \\ 
\qtyrange[range-units = repeat]{2}{4}{\degreeCelsius} \\ 
\qtyrange[range-units = single]{2}{4}{\degreeCelsius}
```
rendering:
2 °C to 4 °C
(2 to 4) °C
2 °C to 4 °C
2 to 4 °C

**Comment by fenjalien** [comment]
`num-range` has been added as of 0.3.0
