### ISSUE TITLE
Add units for memory size.

### ISSUE THREAD

**Issue by SebastianJL** [fenjalien/metro#9]
I suggest adding the following units:

| Unit     | Abbreviation | Symbol |
|----------|--------------|--------|
| kilobyte | kB           | kB     |
| megabyte | MB           | MB     |
| gigabyte | GB           | GB     |
| terabyte | TB           | TB     |
| petabyte | PB           | PB     |
|          |              |        |
| kibibyte | KiB          | KiB    |
| mebibyte | MiB          | MiB    |
| gibibyte | GiB          | GiB    |
| tebibyte | TiB          | TiB    |
| pebibyte | PiB          | PiB    |

In case you don't know about binary prefixes see https://en.wikipedia.org/wiki/Byte#Multiple-byte_units

**Comment by SebastianJL** [comment]
While looking around how to do this I noticed the parameter `power-tens` in `#declare-prefix()` but I couldn't figure out what exactly this is for. But it seems to assume that all possible prefixes are a power of ten, which for the binary prefixes is clearly not the case as they are powers of 1024. Can someone elaborate on this?

**Comment by fenjalien** [comment]
Uh that doesn't do anything ':) Its from when I planned to have exponent modes and control options

**Comment by SebastianJL** [comment]
Ah ok. So do you think we could throw it out, since it clashes with these new prefixes?
